package com.hmg.app.flash.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.hmg.app.flash.model.Test;

/**
 * Class _Question was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Question extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> ANSWER = Property.create("answer", String.class);
    public static final Property<String> ANSWER_IMAGE = Property.create("answerImage", String.class);
    public static final Property<String> QUESTION = Property.create("question", String.class);
    public static final Property<String> QUESTION_ID = Property.create("questionId", String.class);
    public static final Property<String> QUESTION_IMAGE = Property.create("questionImage", String.class);
    public static final Property<List<Test>> TESTS = Property.create("tests", List.class);

    public void setAnswer(String answer) {
        writeProperty("answer", answer);
    }
    public String getAnswer() {
        return (String)readProperty("answer");
    }

    public void setAnswerImage(String answerImage) {
        writeProperty("answerImage", answerImage);
    }
    public String getAnswerImage() {
        return (String)readProperty("answerImage");
    }

    public void setQuestion(String question) {
        writeProperty("question", question);
    }
    public String getQuestion() {
        return (String)readProperty("question");
    }

    public void setQuestionId(String questionId) {
        writeProperty("questionId", questionId);
    }
    public String getQuestionId() {
        return (String)readProperty("questionId");
    }

    public void setQuestionImage(String questionImage) {
        writeProperty("questionImage", questionImage);
    }
    public String getQuestionImage() {
        return (String)readProperty("questionImage");
    }

    public void addToTests(Test obj) {
        addToManyTarget("tests", obj, true);
    }
    public void removeFromTests(Test obj) {
        removeToManyTarget("tests", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Test> getTests() {
        return (List<Test>)readProperty("tests");
    }


}
